data_ingestion:
  data_url: https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip
  user_agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
  timeout: 100
  download_status: False
  external_path: data/external/sms_spam_collection.zip
  raw_dir: data/raw/

data_processor:
  raw_data_path: data/raw/SMSSpamCollection
  processed_data_path: data/processed/sms_data.csv
  random_seed: 42

data_splitter:
  processed_data_path: data/processed/sms_data.csv
  train_data_path: data/train/train_data.csv
  test_data_path: data/test/test_data.csv
  test_size_pct: 0.2
  random_seed: 42

data_standardizer:
  train_data_path: data/train/train_data.csv
  test_data_path: data/test/test_data.csv
  train_matrix_path: data/train/train_sparse_matrix.npz
  test_matrix_path: data/test/test_sparse_matrix.npz
  standardizer_path: models/standardizers/standardizer.joblib

model_trainer:
  train_matrix_path: data/train/train_sparse_matrix.npz
  model_path: models/trained/model.joblib

model_evaluation:
  train_matrix_path: data/train/train_sparse_matrix.npz
  test_matrix_path: data/test/test_sparse_matrix.npz
  model_path: models/trained/model.joblib
  scores_path: models/scores/model_scores.json
  predictions_dir: models/predictions/